meta_product_name: "Yumster"
meta_title: "Yumster - Simple and quick recipe ideas to cook and utilize leftover ingredients"
meta_description: "Offering quick recipes with minimal ingredients"
meta_image: "hamburi.png" # should exist in `app/assets/images/`
